version: '3.3'

services:
  db:
    image: postgres
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash init.sh
    volumes:
      - ./:/code/react
    ports:
      - "3000:3000"
    depends_on:
      - db
      - frontend
